-- Bennu Rising - New Improved Secured Schema
-- This schema implements a UUID-linked Profiles table for robust RBAC.

-- 1. Create Tables
-- Update existing identity columns to GENERATED BY DEFAULT
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND is_identity = 'YES'
          AND identity_generation = 'ALWAYS'
    LOOP
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I SET GENERATED BY DEFAULT', r.table_name, r.column_name);
    END LOOP;
END $$;

-- Legacy Whitelist (Keep for migration and initial authorization)
CREATE TABLE IF NOT EXISTS public.admin_whitelist (
    email text NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    role text DEFAULT 'content_manager'::text
);

-- NEW: Profiles Table (Linked to Auth.Users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email text UNIQUE NOT NULL,
    role text DEFAULT 'content_manager'::text,
    full_name text,
    avatar_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.blog_posts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    excerpt text,
    content text,
    author text,
    image_url text,
    category text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    approval_status text DEFAULT 'published'::text,
    author_email text,
    author_id uuid REFERENCES public.profiles(id),
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.donation_funds (
    id text NOT NULL PRIMARY KEY,
    name text NOT NULL,
    is_active boolean DEFAULT true,
    display_order integer GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE IF NOT EXISTS public.donations (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    donor_name text,
    donor_email text,
    amount numeric,
    fund_id text REFERENCES public.donation_funds(id),
    status text,
    payment_id text,
    frequency text,
    pan_number text,
    is_verified boolean DEFAULT false,
    volunteer_id integer, -- Linked in trigger/app logic
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.gallery_albums (
    id text NOT NULL PRIMARY KEY,
    title text,
    cover_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    approval_status text DEFAULT 'published'::text,
    author_email text,
    author_id uuid REFERENCES public.profiles(id),
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.gallery_images (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id text REFERENCES public.gallery_albums(id) ON DELETE CASCADE,
    image_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.impact_stats (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text,
    value text,
    description text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY,
    approval_status text DEFAULT 'published'::text,
    author_email text,
    author_id uuid REFERENCES public.profiles(id),
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.impact_stories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    description text,
    author text,
    location text,
    image_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    approval_status text DEFAULT 'published'::text,
    author_email text,
    author_id uuid REFERENCES public.profiles(id),
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.mission_groups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    description text,
    color text,
    icon text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE IF NOT EXISTS public.mission_causes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer REFERENCES public.mission_groups(id) ON DELETE CASCADE,
    title text,
    description text,
    icon text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY,
    approval_status text DEFAULT 'published'::text,
    author_email text,
    author_id uuid REFERENCES public.profiles(id),
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text UNIQUE,
    subscribed_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.partnership_inquiries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_name text,
    organization text,
    email text,
    phone text,
    inquiry_type text,
    message text,
    status text DEFAULT 'new'::text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.system_settings (
    key text NOT NULL PRIMARY KEY,
    value text,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.team_members (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    role text,
    bio text,
    image_url text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY,
    approval_status text DEFAULT 'published'::text,
    author_email text,
    author_id uuid REFERENCES public.profiles(id),
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.testimonials (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    role text,
    content text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    approval_status text DEFAULT 'published'::text,
    author_email text,
    author_id uuid REFERENCES public.profiles(id),
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.volunteer_applications (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text,
    last_name text,
    email text,
    phone text,
    interest text,
    status text DEFAULT 'pending'::text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    amount_paid numeric,
    payment_id text,
    application_type text DEFAULT 'volunteer'::text
);

-- Ensure author_id columns exist (for migration of existing tables)
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS author_id uuid REFERENCES public.profiles(id);
ALTER TABLE public.gallery_albums ADD COLUMN IF NOT EXISTS author_id uuid REFERENCES public.profiles(id);
ALTER TABLE public.impact_stats ADD COLUMN IF NOT EXISTS author_id uuid REFERENCES public.profiles(id);
ALTER TABLE public.impact_stories ADD COLUMN IF NOT EXISTS author_id uuid REFERENCES public.profiles(id);
ALTER TABLE public.mission_causes ADD COLUMN IF NOT EXISTS author_id uuid REFERENCES public.profiles(id);
ALTER TABLE public.team_members ADD COLUMN IF NOT EXISTS author_id uuid REFERENCES public.profiles(id);
ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS author_id uuid REFERENCES public.profiles(id);

-- 2. Functions & Triggers

-- Function to handle new user signups
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (
    new.id,
    new.email,
    COALESCE(
      (SELECT role FROM public.admin_whitelist WHERE lower(email) = lower(new.email)),
      'content_manager'
    )
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for automatic profile creation
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Improved is_admin function (UUID based)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
begin
  return (auth.role() = 'authenticated' AND exists (
    select 1 from public.profiles
    where id = auth.uid()
    AND role IN ('super_admin', 'content_manager', 'content_creator')
  ));
end;
$$;

-- Improved get_admin_role function (UUID based)
CREATE OR REPLACE FUNCTION public.get_admin_role()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  user_role text;
BEGIN
  SELECT role INTO user_role FROM public.profiles WHERE id = auth.uid();
  RETURN user_role;
END;
$$;

-- 3. Seed Data

INSERT INTO public.admin_whitelist (email, role) VALUES
('ronin@bennurising.org', 'super_admin'),
('sreerampillai158@gmail.com', 'super_admin'),
('supersain18@gmail.com', 'super_admin'),
('YOUR_ADMIN_EMAIL', 'super_admin')
ON CONFLICT (email) DO UPDATE SET role = EXCLUDED.role;

-- Migration: Create profiles for existing auth users who are in the whitelist
INSERT INTO public.profiles (id, email, role)
SELECT u.id, u.email, w.role
FROM auth.users u
JOIN public.admin_whitelist w ON lower(u.email) = lower(w.email)
ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role;

INSERT INTO public.donation_funds (id, name, is_active) VALUES
('general', 'General Fund (Where Needed Most)', true),
('armed_forces', 'Armed Forces & Police Welfare', true),
('mental_health', 'Mental Health & Rehab Centers', true),
('tribal_edu', 'Tribal Education & Girl Child', true),
('medical', 'Medical Aid (Cancer/Thalassemia/Autism)', true),
('disaster', 'Disaster Relief & Environment', true)
ON CONFLICT DO NOTHING;

-- 4. Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_whitelist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donation_funds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.impact_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.impact_stories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mission_causes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mission_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partnership_inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.volunteer_applications ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies

-- Profiles Policies
DROP POLICY IF EXISTS "Public profiles are readable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are readable by everyone" ON public.profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
DROP POLICY IF EXISTS "Admins can manage all profiles" ON public.profiles;
CREATE POLICY "Admins can manage all profiles" ON public.profiles FOR ALL USING (public.is_admin());

-- Whitelist Policies
DROP POLICY IF EXISTS "Admins manage whitelist" ON public.admin_whitelist;
CREATE POLICY "Admins manage whitelist" ON public.admin_whitelist USING (public.is_admin());

-- Content Policies (Using new UUID-based functions)
DROP POLICY IF EXISTS "Public read albums" ON public.gallery_albums;
CREATE POLICY "Public read albums" ON public.gallery_albums FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read blog" ON public.blog_posts;
CREATE POLICY "Public read blog" ON public.blog_posts FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read funds" ON public.donation_funds;
CREATE POLICY "Public read funds" ON public.donation_funds FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read images" ON public.gallery_images;
CREATE POLICY "Public read images" ON public.gallery_images FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read mission causes" ON public.mission_causes;
CREATE POLICY "Public read mission causes" ON public.mission_causes FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read mission groups" ON public.mission_groups;
CREATE POLICY "Public read mission groups" ON public.mission_groups FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read settings" ON public.system_settings;
CREATE POLICY "Public read settings" ON public.system_settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read stats" ON public.impact_stats;
CREATE POLICY "Public read stats" ON public.impact_stats FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read stories" ON public.impact_stories;
CREATE POLICY "Public read stories" ON public.impact_stories FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read team" ON public.team_members;
CREATE POLICY "Public read team" ON public.team_members FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read testimonials" ON public.testimonials;
CREATE POLICY "Public read testimonials" ON public.testimonials FOR SELECT USING (approval_status = 'published' OR public.is_admin());

-- Admin/Manager Full Access
DROP POLICY IF EXISTS "Managers manage albums" ON public.gallery_albums;
CREATE POLICY "Managers manage albums" ON public.gallery_albums FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage blog" ON public.blog_posts;
CREATE POLICY "Managers manage blog" ON public.blog_posts FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage mission causes" ON public.mission_causes;
CREATE POLICY "Managers manage mission causes" ON public.mission_causes FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage stats" ON public.impact_stats;
CREATE POLICY "Managers manage stats" ON public.impact_stats FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage stories" ON public.impact_stories;
CREATE POLICY "Managers manage stories" ON public.impact_stories FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage team" ON public.team_members;
CREATE POLICY "Managers manage team" ON public.team_members FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage testimonials" ON public.testimonials;
CREATE POLICY "Managers manage testimonials" ON public.testimonials FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));

-- Creator Policies
DROP POLICY IF EXISTS "Creators manage own blog" ON public.blog_posts;
CREATE POLICY "Creators manage own blog" ON public.blog_posts FOR ALL USING (public.get_admin_role() = 'content_creator' AND author_id = auth.uid());
DROP POLICY IF EXISTS "Creators manage own albums" ON public.gallery_albums;
CREATE POLICY "Creators manage own albums" ON public.gallery_albums FOR ALL USING (public.get_admin_role() = 'content_creator' AND author_id = auth.uid());
DROP POLICY IF EXISTS "Creators manage own stats" ON public.impact_stats;
CREATE POLICY "Creators manage own stats" ON public.impact_stats FOR ALL USING (public.get_admin_role() = 'content_creator' AND author_id = auth.uid());
DROP POLICY IF EXISTS "Creators manage own stories" ON public.impact_stories;
CREATE POLICY "Creators manage own stories" ON public.impact_stories FOR ALL USING (public.get_admin_role() = 'content_creator' AND author_id = auth.uid());
DROP POLICY IF EXISTS "Creators manage own mission causes" ON public.mission_causes;
CREATE POLICY "Creators manage own mission causes" ON public.mission_causes FOR ALL USING (public.get_admin_role() = 'content_creator' AND author_id = auth.uid());
DROP POLICY IF EXISTS "Creators manage own team" ON public.team_members;
CREATE POLICY "Creators manage own team" ON public.team_members FOR ALL USING (public.get_admin_role() = 'content_creator' AND author_id = auth.uid());
DROP POLICY IF EXISTS "Creators manage own testimonials" ON public.testimonials;
CREATE POLICY "Creators manage own testimonials" ON public.testimonials FOR ALL USING (public.get_admin_role() = 'content_creator' AND author_id = auth.uid());

-- Public Submissions
DROP POLICY IF EXISTS "Public insert donations" ON public.donations;
CREATE POLICY "Public insert donations" ON public.donations FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admin read donations" ON public.donations;
CREATE POLICY "Admin read donations" ON public.donations FOR SELECT USING (public.is_admin());
DROP POLICY IF EXISTS "Public insert newsletter" ON public.newsletter_subscribers;
CREATE POLICY "Public insert newsletter" ON public.newsletter_subscribers FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public insert partners" ON public.partnership_inquiries;
CREATE POLICY "Public insert partners" ON public.partnership_inquiries FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public insert volunteers" ON public.volunteer_applications;
CREATE POLICY "Public insert volunteers" ON public.volunteer_applications FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admin read volunteers" ON public.volunteer_applications;
CREATE POLICY "Admin read volunteers" ON public.volunteer_applications FOR SELECT USING (public.is_admin());

-- Storage Policies
-- (Assumes 'images' bucket exists)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'images' );
DROP POLICY IF EXISTS "Admin Upload Access" ON storage.objects;
CREATE POLICY "Admin Upload Access" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'images' AND public.is_admin() );
DROP POLICY IF EXISTS "Admin Update Access" ON storage.objects;
CREATE POLICY "Admin Update Access" ON storage.objects FOR UPDATE USING ( bucket_id = 'images' AND public.is_admin() );
DROP POLICY IF EXISTS "Admin Delete Access" ON storage.objects;
CREATE POLICY "Admin Delete Access" ON storage.objects FOR DELETE USING ( bucket_id = 'images' AND public.is_admin() );
