-- 1. Create Tables
-- Update existing identity columns to GENERATED BY DEFAULT
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND is_identity = 'YES'
          AND identity_generation = 'ALWAYS'
    LOOP
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I SET GENERATED BY DEFAULT', r.table_name, r.column_name);
    END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS public.admin_whitelist (
    email text NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    role text DEFAULT 'content_manager'::text
);

CREATE TABLE IF NOT EXISTS public.blog_posts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    excerpt text,
    content text,
    author text,
    image_url text,
    category text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    approval_status text DEFAULT 'published'::text,
    author_email text,
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.donation_funds (
    id text NOT NULL PRIMARY KEY,
    name text NOT NULL,
    is_active boolean DEFAULT true,
    display_order integer GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE IF NOT EXISTS public.donations (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    donor_name text,
    donor_email text,
    amount numeric,
    fund_id text REFERENCES public.donation_funds(id),
    status text,
    payment_id text,
    frequency text,
    pan_number text,
    is_verified boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.gallery_albums (
    id text NOT NULL PRIMARY KEY,
    title text,
    cover_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    approval_status text DEFAULT 'published'::text,
    author_email text,
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.gallery_images (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id text REFERENCES public.gallery_albums(id) ON DELETE CASCADE,
    image_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.impact_stats (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text,
    value text,
    description text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY,
    approval_status text DEFAULT 'published'::text,
    author_email text,
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.impact_stories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    description text,
    author text,
    location text,
    image_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    approval_status text DEFAULT 'published'::text,
    author_email text,
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.mission_groups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    description text,
    color text,
    icon text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE IF NOT EXISTS public.mission_causes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer REFERENCES public.mission_groups(id) ON DELETE CASCADE,
    title text,
    description text,
    icon text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY,
    approval_status text DEFAULT 'published'::text,
    author_email text,
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text UNIQUE,
    subscribed_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.partnership_inquiries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_name text,
    organization text,
    email text,
    phone text,
    inquiry_type text,
    message text,
    status text DEFAULT 'new'::text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.system_settings (
    key text NOT NULL PRIMARY KEY,
    value text,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.team_members (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    role text,
    bio text,
    image_url text,
    display_order integer GENERATED BY DEFAULT AS IDENTITY,
    approval_status text DEFAULT 'published'::text,
    author_email text,
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.testimonials (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    role text,
    content text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    approval_status text DEFAULT 'published'::text,
    author_email text,
    reviewer_comments text
);

CREATE TABLE IF NOT EXISTS public.volunteer_applications (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text,
    last_name text,
    email text,
    phone text,
    interest text,
    status text DEFAULT 'pending'::text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    amount_paid numeric,
    payment_id text,
    application_type text DEFAULT 'volunteer'::text
);

-- 2. Insert Data
-- Add approval workflow columns to existing tables
DO $$
BEGIN
  -- Content Approval Workflow Columns
  if not exists (select 1 from information_schema.columns where table_name = 'blog_posts' and column_name = 'approval_status') then
    alter table public.blog_posts add column approval_status text default 'published';
    alter table public.blog_posts add column author_email text;
    alter table public.blog_posts add column reviewer_comments text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name = 'gallery_albums' and column_name = 'approval_status') then
    alter table public.gallery_albums add column approval_status text default 'published';
    alter table public.gallery_albums add column author_email text;
    alter table public.gallery_albums add column reviewer_comments text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name = 'impact_stats' and column_name = 'approval_status') then
    alter table public.impact_stats add column approval_status text default 'published';
    alter table public.impact_stats add column author_email text;
    alter table public.impact_stats add column reviewer_comments text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name = 'impact_stories' and column_name = 'approval_status') then
    alter table public.impact_stories add column approval_status text default 'published';
    alter table public.impact_stories add column author_email text;
    alter table public.impact_stories add column reviewer_comments text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name = 'mission_causes' and column_name = 'approval_status') then
    alter table public.mission_causes add column approval_status text default 'published';
    alter table public.mission_causes add column author_email text;
    alter table public.mission_causes add column reviewer_comments text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name = 'team_members' and column_name = 'approval_status') then
    alter table public.team_members add column approval_status text default 'published';
    alter table public.team_members add column author_email text;
    alter table public.team_members add column reviewer_comments text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name = 'testimonials' and column_name = 'approval_status') then
    alter table public.testimonials add column approval_status text default 'published';
    alter table public.testimonials add column author_email text;
    alter table public.testimonials add column reviewer_comments text;
  end if;
END $$;

INSERT INTO public.admin_whitelist (email, created_at, role) VALUES
('ronin@bennurising.org', '2025-11-29 03:43:32+00', 'super_admin'),
('sreerampillai158@gmail.com', '2025-11-29 11:18:20+00', 'super_admin'),
('supersain18@gmail.com', '2025-11-01 11:25:55+00', 'super_admin')
ON CONFLICT DO NOTHING;

INSERT INTO public.donation_funds (id, name, is_active) VALUES
('general', 'General Fund (Where Needed Most)', true),
('armed_forces', 'Armed Forces & Police Welfare', true),
('mental_health', 'Mental Health & Rehab Centers', true),
('tribal_edu', 'Tribal Education & Girl Child', true),
('medical', 'Medical Aid (Cancer/Thalassemia/Autism)', true),
('disaster', 'Disaster Relief & Environment', true)
ON CONFLICT DO NOTHING;

INSERT INTO public.mission_groups (title, description, color, icon) VALUES
('Pillar 1 — Individual Transformation & Mental Health', 'Focusing on mental health, emotional resilience, addiction recovery, and holistic healing.', 'text-brand-red', 'Brain'),
('Pillar 2 — Community Health & Development', 'Focusing on public health, women & child welfare, preventive healthcare, and grassroots interventions.', 'text-brand-blue', 'Users'),
('Pillar 3 — Disaster Response & Resilience', 'Focusing on emergency relief, psychological first aid, rehabilitation, and disaster preparedness.', 'text-brand-green', 'Shield'),
('Pillar 4 — Research, Policy & Advocacy', 'Focusing on data collection, policy research, government engagement, and knowledge creation.', 'text-purple-600', 'FileText')
ON CONFLICT DO NOTHING;

INSERT INTO public.mission_causes (group_id, title, description, icon) VALUES
(1, 'Mental Health Care', 'Counseling and therapy access.', 'Brain'),
(1, 'Emotional Resilience', 'Building emotional strength and coping mechanisms.', 'Heart'),
(1, 'Addiction Recovery', 'Holistic rehabilitation and de-addiction programs.', 'Activity'),
(1, 'Yoga & Holistic Healing', 'Integrating yoga and traditional wellness practices.', 'Sun'),
(2, 'Public Health Programs', 'Community-wide health initiatives.', 'Stethoscope'),
(2, 'Women & Child Welfare', 'Empowering and protecting vulnerable demographics.', 'Users'),
(2, 'Preventive Healthcare', 'Awareness and early intervention programs.', 'ShieldCheck'),
(2, 'Grassroots Interventions', 'Direct community engagement and support.', 'HandHeart'),
(3, 'Emergency Relief', 'Providing food, medical aid, and immediate assistance.', 'Tent'),
(3, 'Psychological First Aid', 'Mental health support during crises.', 'HeartHandshake'),
(3, 'Rehabilitation & Livelihood', 'Helping communities rebuild and recover economically.', 'Briefcase'),
(3, 'Disaster Preparedness', 'Training communities for future resilience.', 'GraduationCap'),
(4, 'Data Collection & Impact', 'Measuring and analyzing program outcomes.', 'TrendingUp'),
(4, 'Policy Research', 'Developing evidence-based recommendations.', 'Search'),
(4, 'Government Engagement', 'Collaborating with authorities for systemic change.', 'Landmark'),
(4, 'Training & Capacity Building', 'Empowering individuals and organizations.', 'Award'),
(4, 'Knowledge Creation', 'Publishing reports, studies, and educational materials.', 'BookOpen')
ON CONFLICT DO NOTHING;

INSERT INTO public.system_settings (key, value) VALUES
('vol_roles_title', ''),
('vol_roles_json', '[{"title":"Medical Practitioner","desc":"Test","icon":"Heart"},{"title":"TechWhiz","desc":"Test","icon":"Activity"},{"title":"Finance Intern","desc":"test","icon":"HandHeart"}]')
ON CONFLICT DO NOTHING;

-- 3. Create Admin Function
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
begin
  return (auth.role() = 'authenticated' AND exists (
    select 1 from public.admin_whitelist
    where lower(email) = lower(auth.jwt() ->> 'email')
  ));
end;
$$;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.admin_whitelist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donation_funds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.impact_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.impact_stories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mission_causes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mission_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partnership_inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.volunteer_applications ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies
-- 1. Create a helper function to get the user's specific role
CREATE OR REPLACE FUNCTION public.get_admin_role()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  user_role text;
BEGIN
  SELECT role INTO user_role FROM public.admin_whitelist WHERE lower(email) = lower(auth.jwt() ->> 'email');
  RETURN user_role;
END;
$$;

-- Public Read Access (Restricted)
DROP POLICY IF EXISTS "Public read albums" ON public.gallery_albums;
CREATE POLICY "Public read albums" ON public.gallery_albums FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read blog" ON public.blog_posts;
CREATE POLICY "Public read blog" ON public.blog_posts FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read funds" ON public.donation_funds;
CREATE POLICY "Public read funds" ON public.donation_funds FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read images" ON public.gallery_images;
CREATE POLICY "Public read images" ON public.gallery_images FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read mission causes" ON public.mission_causes;
CREATE POLICY "Public read mission causes" ON public.mission_causes FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read mission groups" ON public.mission_groups;
CREATE POLICY "Public read mission groups" ON public.mission_groups FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read settings" ON public.system_settings;
CREATE POLICY "Public read settings" ON public.system_settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read stats" ON public.impact_stats;
CREATE POLICY "Public read stats" ON public.impact_stats FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read stories" ON public.impact_stories;
CREATE POLICY "Public read stories" ON public.impact_stories FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read team" ON public.team_members;
CREATE POLICY "Public read team" ON public.team_members FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read testimonials" ON public.testimonials;
CREATE POLICY "Public read testimonials" ON public.testimonials FOR SELECT USING (approval_status = 'published' OR public.is_admin());
DROP POLICY IF EXISTS "Public read whitelist" ON public.admin_whitelist;
CREATE POLICY "Public read whitelist" ON public.admin_whitelist FOR SELECT USING (public.is_admin());

-- Public Insert Access
DROP POLICY IF EXISTS "Public insert donations" ON public.donations;
-- Security Fix: Removed public insert policy for donations. Donations MUST go through the secure Edge Function.
DROP POLICY IF EXISTS "Public read donations" ON public.donations;
CREATE POLICY "Public read donations" ON public.donations FOR SELECT USING (public.is_admin());
DROP POLICY IF EXISTS "Public insert newsletter" ON public.newsletter_subscribers;
CREATE POLICY "Public insert newsletter" ON public.newsletter_subscribers FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public insert partners" ON public.partnership_inquiries;
CREATE POLICY "Public insert partners" ON public.partnership_inquiries FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public insert volunteers" ON public.volunteer_applications;
CREATE POLICY "Public insert volunteers" ON public.volunteer_applications FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public read volunteers" ON public.volunteer_applications;
CREATE POLICY "Public read volunteers" ON public.volunteer_applications FOR SELECT USING (public.is_admin());
DROP POLICY IF EXISTS "Public update volunteers" ON public.volunteer_applications;
-- No public update allowed on volunteers

-- Admin Full Access (Managers & Super Admins)
DROP POLICY IF EXISTS "Managers manage albums" ON public.gallery_albums;
CREATE POLICY "Managers manage albums" ON public.gallery_albums FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage blog" ON public.blog_posts;
CREATE POLICY "Managers manage blog" ON public.blog_posts FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage mission causes" ON public.mission_causes;
CREATE POLICY "Managers manage mission causes" ON public.mission_causes FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage stats" ON public.impact_stats;
CREATE POLICY "Managers manage stats" ON public.impact_stats FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage stories" ON public.impact_stories;
CREATE POLICY "Managers manage stories" ON public.impact_stories FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage team" ON public.team_members;
CREATE POLICY "Managers manage team" ON public.team_members FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));
DROP POLICY IF EXISTS "Managers manage testimonials" ON public.testimonials;
CREATE POLICY "Managers manage testimonials" ON public.testimonials FOR ALL USING (public.get_admin_role() IN ('super_admin', 'content_manager'));

-- Content Creator Access (Own content only, no direct publishing)
-- Blog Posts
DROP POLICY IF EXISTS "Creators read own blog" ON public.blog_posts;
CREATE POLICY "Creators read own blog" ON public.blog_posts FOR SELECT USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');
DROP POLICY IF EXISTS "Creators insert own blog" ON public.blog_posts;
CREATE POLICY "Creators insert own blog" ON public.blog_posts FOR INSERT WITH CHECK (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email' AND approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators update own blog" ON public.blog_posts;
CREATE POLICY "Creators update own blog" ON public.blog_posts FOR UPDATE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email') WITH CHECK (approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators delete own blog" ON public.blog_posts;
CREATE POLICY "Creators delete own blog" ON public.blog_posts FOR DELETE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');

-- Gallery Albums
DROP POLICY IF EXISTS "Creators read own albums" ON public.gallery_albums;
CREATE POLICY "Creators read own albums" ON public.gallery_albums FOR SELECT USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');
DROP POLICY IF EXISTS "Creators insert own albums" ON public.gallery_albums;
CREATE POLICY "Creators insert own albums" ON public.gallery_albums FOR INSERT WITH CHECK (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email' AND approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators update own albums" ON public.gallery_albums;
CREATE POLICY "Creators update own albums" ON public.gallery_albums FOR UPDATE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email') WITH CHECK (approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators delete own albums" ON public.gallery_albums;
CREATE POLICY "Creators delete own albums" ON public.gallery_albums FOR DELETE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');

-- Impact Stats
DROP POLICY IF EXISTS "Creators read own stats" ON public.impact_stats;
CREATE POLICY "Creators read own stats" ON public.impact_stats FOR SELECT USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');
DROP POLICY IF EXISTS "Creators insert own stats" ON public.impact_stats;
CREATE POLICY "Creators insert own stats" ON public.impact_stats FOR INSERT WITH CHECK (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email' AND approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators update own stats" ON public.impact_stats;
CREATE POLICY "Creators update own stats" ON public.impact_stats FOR UPDATE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email') WITH CHECK (approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators delete own stats" ON public.impact_stats;
CREATE POLICY "Creators delete own stats" ON public.impact_stats FOR DELETE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');

-- Impact Stories
DROP POLICY IF EXISTS "Creators read own stories" ON public.impact_stories;
CREATE POLICY "Creators read own stories" ON public.impact_stories FOR SELECT USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');
DROP POLICY IF EXISTS "Creators insert own stories" ON public.impact_stories;
CREATE POLICY "Creators insert own stories" ON public.impact_stories FOR INSERT WITH CHECK (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email' AND approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators update own stories" ON public.impact_stories;
CREATE POLICY "Creators update own stories" ON public.impact_stories FOR UPDATE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email') WITH CHECK (approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators delete own stories" ON public.impact_stories;
CREATE POLICY "Creators delete own stories" ON public.impact_stories FOR DELETE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');

-- Mission Causes
DROP POLICY IF EXISTS "Creators read own mission causes" ON public.mission_causes;
CREATE POLICY "Creators read own mission causes" ON public.mission_causes FOR SELECT USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');
DROP POLICY IF EXISTS "Creators insert own mission causes" ON public.mission_causes;
CREATE POLICY "Creators insert own mission causes" ON public.mission_causes FOR INSERT WITH CHECK (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email' AND approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators update own mission causes" ON public.mission_causes;
CREATE POLICY "Creators update own mission causes" ON public.mission_causes FOR UPDATE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email') WITH CHECK (approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators delete own mission causes" ON public.mission_causes;
CREATE POLICY "Creators delete own mission causes" ON public.mission_causes FOR DELETE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');

-- Team Members
DROP POLICY IF EXISTS "Creators read own team" ON public.team_members;
CREATE POLICY "Creators read own team" ON public.team_members FOR SELECT USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');
DROP POLICY IF EXISTS "Creators insert own team" ON public.team_members;
CREATE POLICY "Creators insert own team" ON public.team_members FOR INSERT WITH CHECK (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email' AND approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators update own team" ON public.team_members;
CREATE POLICY "Creators update own team" ON public.team_members FOR UPDATE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email') WITH CHECK (approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators delete own team" ON public.team_members;
CREATE POLICY "Creators delete own team" ON public.team_members FOR DELETE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');

-- Testimonials
DROP POLICY IF EXISTS "Creators read own testimonials" ON public.testimonials;
CREATE POLICY "Creators read own testimonials" ON public.testimonials FOR SELECT USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');
DROP POLICY IF EXISTS "Creators insert own testimonials" ON public.testimonials;
CREATE POLICY "Creators insert own testimonials" ON public.testimonials FOR INSERT WITH CHECK (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email' AND approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators update own testimonials" ON public.testimonials;
CREATE POLICY "Creators update own testimonials" ON public.testimonials FOR UPDATE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email') WITH CHECK (approval_status IN ('draft', 'pending'));
DROP POLICY IF EXISTS "Creators delete own testimonials" ON public.testimonials;
CREATE POLICY "Creators delete own testimonials" ON public.testimonials FOR DELETE USING (public.get_admin_role() = 'content_creator' AND author_email = auth.jwt() ->> 'email');

-- Other Admin Full Access (Generic)
DROP POLICY IF EXISTS "Admin manage funds" ON public.donation_funds;
CREATE POLICY "Admin manage funds" ON public.donation_funds USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage images" ON public.gallery_images;
CREATE POLICY "Admin manage images" ON public.gallery_images USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage mission groups" ON public.mission_groups;
CREATE POLICY "Admin manage mission groups" ON public.mission_groups USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage partners" ON public.partnership_inquiries;
CREATE POLICY "Admin manage partners" ON public.partnership_inquiries USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage settings" ON public.system_settings;
CREATE POLICY "Admin manage settings" ON public.system_settings USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage volunteers" ON public.volunteer_applications;
CREATE POLICY "Admin manage volunteers" ON public.volunteer_applications USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage whitelist" ON public.admin_whitelist;
CREATE POLICY "Admin manage whitelist" ON public.admin_whitelist USING (public.is_admin());
DROP POLICY IF EXISTS "Admin read donations" ON public.donations;
CREATE POLICY "Admin read donations" ON public.donations FOR SELECT USING (public.is_admin());
DROP POLICY IF EXISTS "Admin read newsletter" ON public.newsletter_subscribers;
CREATE POLICY "Admin read newsletter" ON public.newsletter_subscribers FOR SELECT USING (public.is_admin());

-- 4. Storage Bucket Setup
insert into storage.buckets (id, name, public) values ('images', 'images', true) on conflict do nothing;
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
create policy "Public Access" on storage.objects for select using ( bucket_id = 'images' );
DROP POLICY IF EXISTS "Admin Upload Access" ON storage.objects;
create policy "Admin Upload Access" on storage.objects for insert with check ( bucket_id = 'images' and public.is_admin() );
DROP POLICY IF EXISTS "Admin Update Access" ON storage.objects;
create policy "Admin Update Access" on storage.objects for update using ( bucket_id = 'images' and public.is_admin() );
DROP POLICY IF EXISTS "Admin Delete Access" ON storage.objects;
create policy "Admin Delete Access" on storage.objects for delete using ( bucket_id = 'images' and public.is_admin() );
