-- Volunteer & Intern Portal Schema

-- Create tables

CREATE TABLE IF NOT EXISTS public.portal_tasks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed')),
    due_date timestamp with time zone,
    created_by uuid REFERENCES auth.users(id),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.portal_goals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    target_value integer DEFAULT 100,
    current_value integer DEFAULT 0,
    unit text,
    is_system_goal boolean DEFAULT false,
    created_by uuid REFERENCES auth.users(id),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.portal_certificates (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    certificate_type text NOT NULL CHECK (certificate_type IN ('intern', 'volunteer')),
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'issued')),
    approved_by uuid REFERENCES auth.users(id),
    approved_at timestamp with time zone,
    file_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.whatsapp_messages_queue (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    message_type text,
    message_content text NOT NULL,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    scheduled_for timestamp with time zone DEFAULT timezone('utc'::text, now()),
    sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- RLS Policies

ALTER TABLE public.portal_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portal_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portal_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_messages_queue ENABLE ROW LEVEL SECURITY;

-- Only admins/super_admins/volunteer_managers can view all. Users can view their own.
-- For simplicity, let's allow users to select their own tasks.
CREATE POLICY "Users can view their own tasks" ON public.portal_tasks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own tasks" ON public.portal_tasks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Admins can do everything on tasks" ON public.portal_tasks FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('super_admin', 'admin', 'volunteer_manager'))
);

CREATE POLICY "Users can view their own goals" ON public.portal_goals FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own goals" ON public.portal_goals FOR INSERT WITH CHECK (auth.uid() = user_id AND is_system_goal = false);
CREATE POLICY "Users can update own goals" ON public.portal_goals FOR UPDATE USING (auth.uid() = user_id AND is_system_goal = false);
CREATE POLICY "Users can update progress on system goals" ON public.portal_goals FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Admins can do everything on goals" ON public.portal_goals FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('super_admin', 'admin', 'volunteer_manager'))
);

CREATE POLICY "Users can view their own certificates" ON public.portal_certificates FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can do everything on certificates" ON public.portal_certificates FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('super_admin', 'admin', 'volunteer_manager'))
);

CREATE POLICY "Admins can do everything on whatsapp queue" ON public.whatsapp_messages_queue FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('super_admin', 'admin', 'volunteer_manager'))
);
